# Start with the base image
# FROM alpine:latest
FROM mcr.microsoft.com/devcontainers/base:alpine-3.20

# Install necessary packages
RUN apk add --no-cache curl

# Switch to vscode user
# switching to USER vscode. This is the most important security practice.
# It prevents the container process from having root access to the underlying container (and potentially the host if escapes occur).
USER vscode

# install bun
RUN curl -fsSL https://bun.sh/install | bash

# add bun to path
ENV BUN_INSTALL="/home/vscode/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"

# server
# NO need to expose in file, VSCode will auto forward (if exposed, VScode will also block these ports, even if the vscode is only open in devcontainer mode)
# EXPOSE 4000
# frontend / vite dev server
# EXPOSE 5173

WORKDIR /workspaces/

# add directory where trail bin located to search path
# DO NOT ADD TO PATH, as trail binary needs to have correct path/traildepot subfolder
# ENV TRAIL_BIN_LOCATION="/workspaces/chinese-learning-app/backend"
# ENV PATH="$TRAIL_BIN_LOCATION:$PATH"

# Copy any necessary files or configurations here
# COPY ./path/to/your/files /path/in/container
